export const recetasTipicas = [
  {
    id: 1,
    nombre: "Tlayudas",
    ingredientes: [
      {
        id: 1,
        nombre: "tlayuda",
        cantidad: 1,
        unidad: "pieza",
        categoria: 4,
      },
      {
        id: 2,
        nombre: "manteca",
        cantidad: 2,
        unidad: "cucharadas",
        categoria: 2,
      },
      {
        id: 3,
        nombre: "frijol molido",
        cantidad: 3,
        unidad: "cucharadas",
        categoria: 2,
      },
      {
        id: 4,
        nombre: "tasajo",
        cantidad: 1,
        unidad: "pieza",
        categoria: 2,
      },
      {
        id: 5,
        nombre: "aguacate",
        cantidad: 1,
        unidad: "rebanada",
        categoria: 3,
      },
      {
        id: 6,
        nombre: "salsa",
        cantidad: 1,
        unidad: "cucharada",
        categoria: 1,
      },
      {
        id: 7,
        nombre: "tomate",
        cantidad: 1,
        unidad: "pieza",
        categoria: 1,
      },
      {
        id: 8,
        nombre: "lechuga",
        cantidad: 1,
        unidad: "pieza",
        categoria: 1,
      },
    ],
    alerta: "Elevada en azúcar",
    leyenda: "precaucion no comer en exceso",
    imagen: "https://i.postimg.cc/3RRYfS1J/imagen-2022-05-14-221802795.png",
  },
  {
    id: 2,
    nombre: "Mole coloradito",
    ingredientes: [
      {
        id: 1,
        nombre: "Chile huajillo",
        cantidad: 50,
        unidad: "gramos",
        categoria: 1,
      },
      {
        id: 2,
        nombre: "chile ancho",
        cantidad: 100,
        unidad: "gramos",
        categoria: 1,
      },
      {
        id: 3,
        nombre: "jitomates",
        cantidad: 2,
        unidad: "piezas",
        categoria: 1,
      },
      {
        id: 4,
        nombre: "cebolla chica",
        cantidad: 1,
        unidad: "pieza",
        categoria: 1,
      },
      {
        id: 5,
        nombre: "ajos pelados",
        cantidad: 2,
        unidad: "piezas",
        categoria: 1,
      },
      {
        id: 6,
        nombre: "aceite",
        cantidad: 4,
        unidad: "cucharadas",
        categoria: 2,
      },
      {
        id: 7,
        nombre: "platano macho",
        cantidad: 1,
        unidad: "pieza",
        categoria: 1,
      },
      {
        id: 8,
        nombre: "pan bolillo",
        cantidad: 1,
        unidad: "pieza",
        categoria: 4,
      },
      {
        id: 9,
        nombre: "ajonjolí",
        cantidad: 2,
        unidad: "cucharadas",
        categoria: 4,
      },
      {
        id: 10,
        nombre: "canela",
        cantidad: 1,
        unidad: "pieza",
        categoria: 0,
      },
      {
        id: 11,
        nombre: "oregano",
        cantidad: 1,
        unidad: "pieza",
        categoria: 0,
      },
      {
        id: 12,
        nombre: "clavos de olor",
        cantidad: 2,
        unidad: "piezas",
        categoria: 0,
      },
      {
        id: 13,
        nombre: "sal",
        cantidad: 1,
        unidad: "pizca",
        categoria: 0,
      },
      {
        id: 14,
        nombre: "Pimienta",
        cantidad: 1,
        unidad: "pizca",
        categoria: 0,
      },
      {
        id: 15,
        nombre: "caldo de pollo",
        cantidad: 2,
        unidad: "tazas",
        categoria: 0,
      },
      {
        id: 16,
        nombre: "Pollo",
        cantidad: 2,
        unidad: "piezas",
        categoria: 2,
      },
    ],
    alerta: "Elevada en azúcar, grasas y energía",
    leyenda: "precaucion no comer en exceso",
    imagen: "https://i.postimg.cc/BZM3Zypj/mole.png",
  },
  {
    id: 3,
    nombre: "Tejate",
    ingredientes: [
      {
        id: 1,
        nombre: "Cacao en polvo",
        cantidad: 3,
        unidad: "cucharadas",
        categoria: 0,
      },
      {
        id: 2,
        nombre: "huesos de mamey",
        cantidad: 2,
        unidad: "piezas",
        categoria: 0,
      },
      {
        id: 3,
        nombre: "maíz",
        cantidad: 1,
        unidad: "kilogramo",
        categoria: 4,
      },
      {
        id: 4,
        nombre: "agua",
        cantidad: 4,
        unidad: "tazas",
        categoria: 0,
      },
      {
        id: 5,
        nombre: "Azúcar",
        cantidad: 2,
        unidad: "cucharadas",
        categoria: 4,
      },
      {
        id: 6,
        nombre: "cubos de hielo",
        cantidad: 3,
        unidad: "piezas",
        categoria: 0,
      },
    ],
    alerta: "Elevada en azúcar",
    leyenda: "precaucion no comer en exceso",
    imagen: "https://i.postimg.cc/MKcbJzH1/image-5-3.png",
  },
  {
    id: 4,
    nombre: "Sopa de guías",
    ingredientes: [
      {
        id: 1,
        nombre: "Guías de milpa",
        cantidad: 1,
        unidad: "taza",
        categoria: 1,
      },
      {
        id: 2,
        nombre: "calabacita",
        cantidad: 2,
        unidad: "piezas",
        categoria: 1,
      },
      {
        id: 3,
        nombre: "chepil",
        cantidad: 1,
        unidad: "rollo",
        categoria: 1,
      },
      {
        id: 4,
        nombre: "Chayotes",
        cantidad: 2,
        unidad: "piezas",
        categoria: 1,
      },
      {
        id: 5,
        nombre: "Elotes tiernos",
        cantidad: 3,
        unidad: "piezas",
        categoria: 4,
      },
      {
        id: 6,
        nombre: "Masa para tortillas",
        cantidad: 100,
        unidad: "gramos",
        categoria: 4,
      },
      {
        id: 7,
        nombre: "Manteca",
        cantidad: 2,
        unidad: "Cucharadas",
        categoria: 2,
      },
    ],
    alerta: "Elevada en azúcar",
    leyenda: "precaucion no comer en exceso",
    imagen: "https://i.postimg.cc/vZKmFd1x/image-5-4.png",
  },
  {
    id: 5,
    nombre: "Tamales oaxaqueños",
    ingredientes: [
      {
        id: 1,
        nombre: "carne de cerdo",
        cantidad: 500,
        unidad: "gramos",
        categoria: 2,
      },
      {
        id: 2,
        nombre: "dientes de ajo",
        cantidad: 3,
        unidad: "dientes",
        categoria: 0,
      },
      {
        id: 3,
        nombre: "cebolla",
        cantidad: 1,
        unidad: "pieza",
        categoria: 1,
      },
      {
        id: 4,
        nombre: "Sal",
        cantidad: 1,
        unidad: "pizca",
        categoria: 0,
      },
      {
        id: 5,
        nombre: "chiles anchos",
        cantidad: 6,
        unidad: "piezas",
        categoria: 1,
      },
      {
        id: 6,
        nombre: "chiles huajillos",
        cantidad: 8,
        unidad: "piezas",
        categoria: 1,
      },
      {
        id: 7,
        nombre: "Jitomates",
        cantidad: 2,
        unidad: "piezas",
        categoria: 1,
      },
      {
        id: 8,
        nombre: "Mejorana seca",
        cantidad: 1,
        unidad: "cucharadita",
        categoria: 0,
      },
      {
        id: 9,
        nombre: "Pimienta",
        cantidad: 1,
        unidad: "cucharadita",
        categoria: 0,
      },
      {
        id: 10,
        nombre: "Clavos de olor",
        cantidad: 2,
        unidad: "piezas",
        categoria: 0,
      },
      {
        id: 11,
        nombre: "Masa de maíz",
        cantidad: 500,
        unidad: "gramos",
        categoria: 4,
      },
      {
        id: 12,
        nombre: "Manteca de cerdo",
        cantidad: 5,
        unidad: "cucharadas",
        categoria: 2,
      },
      {
        id: 13,
        nombre: "Hojas de platano",
        cantidad: 3,
        unidad: "piezas",
        categoria: 0,
      },
    ],
    alerta: "Elevada en azúcar, grasas y energía",
    leyenda: "precaucion no comer en exceso",
    imagen: "https://i.postimg.cc/Qd1zsQCg/image-5-5.png",
  },
];

export const recetasSaludables = [
  {
    id: 1,
    nombre: "Ensalada de nopales con queso",
    imagen: "https://i.postimg.cc/SssVXCSv/image-5-6.png",
    ingredientes: [
      {
        id: 1,
        nombre: "Nopales",
        cantidad: 6,
        unidad: "pieza",
        categoria: 1,
      },
      {
        id: 2,
        nombre: "Cebolla",
        cantidad: 1,
        unidad: "pieza",
        categoria: 1,
      },
      {
        id: 3,
        nombre: "Tomate",
        cantidad: 2,
        unidad: "piezas",
        categoria: 1,
      },
      {
        id: 4,
        nombre: "Queso fresco",
        cantidad: 250,
        unidad: "gramos",
        categoria: 3,
      },
      {
        id: 5,
        nombre: "cilantro",
        cantidad: 2,
        unidad: "piezas",
        categoria: 1,
      },
      {
        id: 6,
        nombre: "Oregano",
        cantidad: 2,
        unidad: "piezas",
        categoria: 0,
      },
      {
        id: 7,
        nombre: "Sal",
        cantidad: 3,
        unidad: "gramos",
        categoria: 0,
      },
    ],
    Nota: "Usar poca sal en su preparacion ",
  },
  {
    id: 2,
    nombre: "Quesadillas al comal de flor de calabaza",
    imagen: "https://i.postimg.cc/V6pTmDqR/image-5-7.png",
    ingredientes: [
      {
        id: 1,
        nombre: "Tortilla",
        cantidad: 2,
        unidad: "piezas",
        categoria: 4,
      },
      {
        id: 2,
        nombre: "Quesillo",
        cantidad: 1,
        unidad: "taza",
        categoria: 3,
      },
      {
        id: 3,
        nombre: "Flor de calabaza",
        cantidad: 1,
        unidad: "taza",
        categoria: 1,
      },
    ],
    Nota: "Usar de preferencia quesillo o queso panela o bajo en grasas ",
  },
  {
    id: 3,
    nombre: "Hotcake de avena y platano",
    imagen: "https://i.postimg.cc/nLLwm6T2/image-5-8.png",
    ingredientes: [
      {
        id: 1,
        nombre: "Avena",
        cantidad: 1,
        unidad: "taza",
        categoria: 3,
      },
      {
        id: 2,
        nombre: "Leche",
        cantidad: 1,
        unidad: "taza",
        categoria: 3,
      },
      {
        id: 3,
        nombre: "Sal",
        cantidad: 1,
        unidad: "pizca",
        categoria: 0,
      },
      {
        id: 4,
        nombre: "Extracto de vainilla",
        cantidad: 10,
        unidad: "mililitros",
        categoria: 0,
      },
      {
        id: 5,
        nombre: "Polvo para hornear",
        cantidad: 6,
        unidad: "gramos",
        categoria: 0,
      },
      {
        id: 6,
        nombre: "Huevo",
        cantidad: 1,
        unidad: "pieza",
        categoria: 3,
      },
      {
        id: 7,
        nombre: "Mantequilla",
        cantidad: 10,
        unidad: "gramos",
        categoria: 3,
      },
    ],
    Nota: "Puedes acompañarlos con frutas de temporadas, preferentemente no tan dulces",
    Nota2: "No usar miel de maple o mermeladas en pacientes diabeticos",
  },
];
