import { Button } from "@nextui-org/react";
import Head from "next/head";
import { ChartP } from "../components/ChartP";
import SwitchTheme from "../components/SwitchTheme";
import styles from "../styles/Home.module.css";
import {signIn} from 'next-auth/react';
import Hero from '/public/Hero.png';
import Image from "next/image";

export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>NutriTech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Bienvenido a NutriTech</h1>
        <Image src={Hero} alt="Hero image" width={700} height={500}/>
        <div className={styles.footer}>  
          <h4>¡Sí tu alimentación quieres mejorar NutriTech debes de usar!</h4>
          <Button color="success" auto ghost onClick={() => signIn()}>Continuar</Button>
        </div>  
      </main>
    </div>
  );
}
